### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mranostay** [mattfors/generic-arduino-serial-gui#1]
What license have you released this under?

**Comment by mattfors** [comment]
GPL, http://www.gnu.org/copyleft/gpl.html

Use it however you like, I intended to do add more display types but just
haven't found time. You making anything interesting?

**Comment by mranostay** [comment]
Geiger counter test application.  Any chance I can convince you to BSD it? :)

**Comment by mattfors** [comment]
That sounds pretty interesting, I'm always looking for little projects for
my resume.  How often do the readings need to get updated on the server? I
worked on something similar to read loadcells on an arduino and update a
server every hour.

**Comment by mranostay** [comment]
http://www.youtube.com/watch?v=507uXzhOjfo

**Comment by mranostay** [comment]
Whatever you choose can you just put in the README.md thanks :)
